name: Validate
description: Check for dead links

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'

    - name: Check for broken internal links
      shell: bash
      run: |
        cp "./hazelcast-docs/lib/load-check-links-playbook.js" "./load-check-links-playbook.js"
        npm i
        npm i -D yaml@2.6.0
        node load-check-links-playbook.js $GITHUB_REPOSITORY $GITHUB_BASE_REF
        ./node_modules/.bin/antora --fetch --to-dir test --log-level=error --log-failure-level=error --extension=@jcahills/antora-link-checker check-links-playbook.yml
