# Checks if the incoming pull request includes any broken internal links

name: Check for dead links

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  check-links:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Current Repo
      uses: actions/checkout@v4
    - name: Validate docs
      uses: ./.github/actions/validate
      with:
        orphan-checker-directory: tutorials
        slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_DOCS }}


