# Checks if the incoming pull request includes any broken internal links

name: Check for dead links

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  check-links:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Check for broken internal links
      env:
        GIT_CREDENTIALS: ${{ secrets.GIT_CREDENTIALS }}
      run: |
        npm i
        npm run-script check-links-local


